"""
038_nw_fer_mapping.py
Маппинг ФЕР раздел ↔ NW (long-table).

Связывает разделы сборников ФЕР с нормализованными видами работ из fer.nw_item.
Один ФЕР раздел может соответствовать нескольким NW (с разной уверенностью / приоритетом).

Источник: «FER_to_NW_mapping_v2.xlsx» — экспертная разметка по 27 in-scope сборникам ФЕР.
"""

from alembic import op
import sqlalchemy as sa


revision = "038_nw_fer_mapping"
down_revision = "037_nw_dictionary"
branch_labels = None
depends_on = None

FER_SCHEMA = "fer"


# 248 mapping rows
NW_FER_MAPPING = [
    {"fer_collection_num": 1, "fer_section_num": 1, "nw_item_code": "NW-003", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Котлован, базовая разработка"},
    {"fer_collection_num": 1, "fer_section_num": 1, "nw_item_code": "NW-005", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Планировка"},
    {"fer_collection_num": 1, "fer_section_num": 1, "nw_item_code": "NW-006", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Насыпи (если в скоупе участка)"},
    {"fer_collection_num": 1, "fer_section_num": 1, "nw_item_code": "NW-008", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Уплотнение основания"},
    {"fer_collection_num": 1, "fer_section_num": 1, "nw_item_code": "NW-010", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Вывоз грунта"},
    {"fer_collection_num": 1, "fer_section_num": 2, "nw_item_code": "NW-001", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Подготовка площадки"},
    {"fer_collection_num": 1, "fer_section_num": 2, "nw_item_code": "NW-002", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Снятие растительного слоя"},
    {"fer_collection_num": 1, "fer_section_num": 2, "nw_item_code": "NW-007", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Обратная засыпка"},
    {"fer_collection_num": 1, "fer_section_num": 2, "nw_item_code": "NW-009", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Водопонижение, крепление откосов"},
    {"fer_collection_num": 1, "fer_section_num": 2, "nw_item_code": "NW-004", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Траншеи под сети как сопутствующее"},
    {"fer_collection_num": 1, "fer_section_num": 3, "nw_item_code": "NW-003", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Только при стройке в зоне вечной мерзлоты — нишево"},
    {"fer_collection_num": 4, "fer_section_num": 1, "nw_item_code": "NW-059", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Бурение скважины водоснабжения"},
    {"fer_collection_num": 4, "fer_section_num": 2, "nw_item_code": "NW-059", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Обсадка скважины"},
    {"fer_collection_num": 4, "fer_section_num": 3, "nw_item_code": "NW-059", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "Тампонаж в составе скважины"},
    {"fer_collection_num": 4, "fer_section_num": 4, "nw_item_code": "NW-059", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Фильтры, откачка, ввод в эксплуатацию"},
    {"fer_collection_num": 4, "fer_section_num": 5, "nw_item_code": "NW-059", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Шахтный колодец как альтернатива скважине"},
    {"fer_collection_num": 4, "fer_section_num": 6, "nw_item_code": "NW-059", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Прочее — низкая уверенность"},
    {"fer_collection_num": 5, "fer_section_num": 1, "nw_item_code": "NW-016", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Свайное основание = основание под фундамент"},
    {"fer_collection_num": 5, "fer_section_num": 1, "nw_item_code": "NW-017", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Армирование забивных/буронабивных"},
    {"fer_collection_num": 5, "fer_section_num": 2, "nw_item_code": "NW-016", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Опускные колодцы — преим. промстрой/гидро"},
    {"fer_collection_num": 5, "fer_section_num": 3, "nw_item_code": "NW-008", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Закрепление = укрепление основания"},
    {"fer_collection_num": 5, "fer_section_num": 3, "nw_item_code": "NW-009", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Часто связано с откосами"},
    {"fer_collection_num": 6, "fer_section_num": 1, "nw_item_code": "NW-017", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Опалубка и армирование монолитного фундамента"},
    {"fer_collection_num": 6, "fer_section_num": 1, "nw_item_code": "NW-018", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Бетонирование фундамента"},
    {"fer_collection_num": 6, "fer_section_num": 2, "nw_item_code": "NW-018", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Фундаменты под промоборудование — преим. вне скоупа"},
    {"fer_collection_num": 6, "fer_section_num": 3, "nw_item_code": "NW-018", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Прочие монолитные работы"},
    {"fer_collection_num": 6, "fer_section_num": 4, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Стены подвалов = наружные стены"},
    {"fer_collection_num": 6, "fer_section_num": 4, "nw_item_code": "NW-018", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Бетонирование стен"},
    {"fer_collection_num": 6, "fer_section_num": 4, "nw_item_code": "NW-084", "mapping_type": "partial", "confidence": "low", "is_primary": False, "notes": "Подпорные стены вне здания"},
    {"fer_collection_num": 6, "fer_section_num": 5, "nw_item_code": "NW-023", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Колонны = несущий каркас"},
    {"fer_collection_num": 6, "fer_section_num": 5, "nw_item_code": "NW-018", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Бетонирование колонн"},
    {"fer_collection_num": 6, "fer_section_num": 6, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Монолитные стены"},
    {"fer_collection_num": 6, "fer_section_num": 6, "nw_item_code": "NW-026", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Перегородки"},
    {"fer_collection_num": 6, "fer_section_num": 6, "nw_item_code": "NW-018", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Бетонирование"},
    {"fer_collection_num": 6, "fer_section_num": 7, "nw_item_code": "NW-023", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Балки/ригели = каркас"},
    {"fer_collection_num": 6, "fer_section_num": 7, "nw_item_code": "NW-018", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Бетонирование"},
    {"fer_collection_num": 6, "fer_section_num": 8, "nw_item_code": "NW-025", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Перекрытия"},
    {"fer_collection_num": 6, "fer_section_num": 8, "nw_item_code": "NW-018", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Бетонирование"},
    {"fer_collection_num": 6, "fer_section_num": 9, "nw_item_code": "NW-018", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Баритобетон — спецзащита от излучения"},
    {"fer_collection_num": 6, "fer_section_num": 10, "nw_item_code": "NW-018", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Тоннели — вне скоупа"},
    {"fer_collection_num": 6, "fer_section_num": 11, "nw_item_code": "NW-018", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Бункера — промстрой"},
    {"fer_collection_num": 6, "fer_section_num": 12, "nw_item_code": "NW-022", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Скользящая опалубка — высотные здания/силосы"},
    {"fer_collection_num": 6, "fer_section_num": 12, "nw_item_code": "NW-024", "mapping_type": "partial", "confidence": "medium", "is_primary": False, "notes": "Стены"},
    {"fer_collection_num": 6, "fer_section_num": 13, "nw_item_code": "NW-061", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Бетонные ёмкости КНС/септиков"},
    {"fer_collection_num": 6, "fer_section_num": 13, "nw_item_code": "NW-060", "mapping_type": "partial", "confidence": "low", "is_primary": False, "notes": "Резервуары водопровода"},
    {"fer_collection_num": 6, "fer_section_num": 14, "nw_item_code": "NW-018", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Емкостные сооружения — преим. промстрой"},
    {"fer_collection_num": 6, "fer_section_num": 15, "nw_item_code": "NW-018", "mapping_type": "composite_part", "confidence": "medium", "is_primary": True, "notes": "Приготовление бетона на стройке — сопровождает все бетонные работы"},
    {"fer_collection_num": 6, "fer_section_num": 16, "nw_item_code": "NW-021", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Монолитные жилые дома"},
    {"fer_collection_num": 6, "fer_section_num": 16, "nw_item_code": "NW-022", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Монолитные общественные здания"},
    {"fer_collection_num": 6, "fer_section_num": 16, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Стены"},
    {"fer_collection_num": 6, "fer_section_num": 16, "nw_item_code": "NW-025", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Перекрытия"},
    {"fer_collection_num": 6, "fer_section_num": 17, "nw_item_code": "NW-024", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Скользящая опалубка стен"},
    {"fer_collection_num": 6, "fer_section_num": 18, "nw_item_code": "NW-025", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "Перекрытия в мелкощитовой опалубке"},
    {"fer_collection_num": 6, "fer_section_num": 19, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "Инвентарная опалубка стен (бадьи)"},
    {"fer_collection_num": 6, "fer_section_num": 19, "nw_item_code": "NW-025", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Перекрытия"},
    {"fer_collection_num": 6, "fer_section_num": 20, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "Инвентарная мелкощитовая опалубка"},
    {"fer_collection_num": 6, "fer_section_num": 20, "nw_item_code": "NW-025", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Перекрытия"},
    {"fer_collection_num": 6, "fer_section_num": 21, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "Инвентарная опалубка (бетононасос)"},
    {"fer_collection_num": 6, "fer_section_num": 21, "nw_item_code": "NW-025", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Перекрытия"},
    {"fer_collection_num": 6, "fer_section_num": 22, "nw_item_code": "NW-018", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Конструкции АЭС — вне скоупа"},
    {"fer_collection_num": 6, "fer_section_num": 23, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Монолитная надземная часть, индустриальная опалубка"},
    {"fer_collection_num": 6, "fer_section_num": 23, "nw_item_code": "NW-025", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Перекрытия"},
    {"fer_collection_num": 6, "fer_section_num": 23, "nw_item_code": "NW-021", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Жилые"},
    {"fer_collection_num": 6, "fer_section_num": 23, "nw_item_code": "NW-022", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Нежилые"},
    {"fer_collection_num": 6, "fer_section_num": 24, "nw_item_code": "NW-018", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Монолитная подземная часть = фундамент/подвал"},
    {"fer_collection_num": 6, "fer_section_num": 24, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Стены подвала"},
    {"fer_collection_num": 7, "fer_section_num": 1, "nw_item_code": "NW-022", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Сборные ж/б производственные здания"},
    {"fer_collection_num": 7, "fer_section_num": 2, "nw_item_code": "NW-061", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Сборные сооружения канализации"},
    {"fer_collection_num": 7, "fer_section_num": 2, "nw_item_code": "NW-060", "mapping_type": "partial", "confidence": "medium", "is_primary": False, "notes": "Сборные сооружения водопровода"},
    {"fer_collection_num": 7, "fer_section_num": 3, "nw_item_code": "NW-022", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Зернохранилища — узкая отрасль"},
    {"fer_collection_num": 7, "fer_section_num": 4, "nw_item_code": "NW-022", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Главные корпуса ТЭС — вне скоупа"},
    {"fer_collection_num": 7, "fer_section_num": 5, "nw_item_code": "NW-021", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Жилые/админбытовые здания"},
    {"fer_collection_num": 7, "fer_section_num": 5, "nw_item_code": "NW-022", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Общественные здания"},
    {"fer_collection_num": 7, "fer_section_num": 6, "nw_item_code": "NW-063", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Камеры/конструкции тепловых сетей"},
    {"fer_collection_num": 7, "fer_section_num": 7, "nw_item_code": "NW-024", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Хризотилцементные стены — устаревшая технология"},
    {"fer_collection_num": 7, "fer_section_num": 8, "nw_item_code": "NW-024", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "ЦСП-стеновые элементы"},
    {"fer_collection_num": 7, "fer_section_num": 8, "nw_item_code": "NW-026", "mapping_type": "partial", "confidence": "low", "is_primary": False, "notes": "ЦСП-перегородки"},
    {"fer_collection_num": 7, "fer_section_num": 9, "nw_item_code": "NW-022", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Конструкции АЭС — вне скоупа"},
    {"fer_collection_num": 8, "fer_section_num": 1, "nw_item_code": "NW-016", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Бутовые основания фундаментов"},
    {"fer_collection_num": 8, "fer_section_num": 1, "nw_item_code": "NW-019", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Гидроизоляция фундамента"},
    {"fer_collection_num": 8, "fer_section_num": 2, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Кирпичные стены"},
    {"fer_collection_num": 8, "fer_section_num": 2, "nw_item_code": "NW-022", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Здания из кирпича"},
    {"fer_collection_num": 8, "fer_section_num": 2, "nw_item_code": "NW-021", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Жилые из кирпича"},
    {"fer_collection_num": 8, "fer_section_num": 3, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Стены из легких блоков (газобетон/пеноблок)"},
    {"fer_collection_num": 8, "fer_section_num": 3, "nw_item_code": "NW-021", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Дома из газоблока"},
    {"fer_collection_num": 8, "fer_section_num": 4, "nw_item_code": "NW-026", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Перегородки из кирпича/блоков"},
    {"fer_collection_num": 8, "fer_section_num": 5, "nw_item_code": "NW-022", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Подоконные плиты, крыльца — мелкие конструктивные"},
    {"fer_collection_num": 8, "fer_section_num": 5, "nw_item_code": "NW-031", "mapping_type": "partial", "confidence": "low", "is_primary": False, "notes": "Часть отделки"},
    {"fer_collection_num": 8, "fer_section_num": 6, "nw_item_code": "NW-022", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Мусоропроводы — внутренняя система зданий"},
    {"fer_collection_num": 8, "fer_section_num": 7, "nw_item_code": "NW-001", "mapping_type": "composite_part", "confidence": "medium", "is_primary": True, "notes": "Леса — оснащение площадки, сопровождают все высотные работы"},
    {"fer_collection_num": 8, "fer_section_num": 8, "nw_item_code": "NW-045", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Печи отопительные — устаревший тип отопления"},
    {"fer_collection_num": 9, "fer_section_num": 1, "nw_item_code": "NW-023", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Металлокаркасы зданий"},
    {"fer_collection_num": 9, "fer_section_num": 1, "nw_item_code": "NW-022", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Металлические здания целиком"},
    {"fer_collection_num": 9, "fer_section_num": 2, "nw_item_code": "NW-022", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Металлические сооружения — резервуары, мачты и т.п."},
    {"fer_collection_num": 9, "fer_section_num": 3, "nw_item_code": "NW-023", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Балки, лестницы, площадки"},
    {"fer_collection_num": 9, "fer_section_num": 4, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Стеновые металлические панели/ограждения"},
    {"fer_collection_num": 9, "fer_section_num": 4, "nw_item_code": "NW-076", "mapping_type": "partial", "confidence": "medium", "is_primary": False, "notes": "Облицовка фасада металлом"},
    {"fer_collection_num": 9, "fer_section_num": 4, "nw_item_code": "NW-075", "mapping_type": "partial", "confidence": "medium", "is_primary": False, "notes": "Подсистема вентфасада (металлокаркас)"},
    {"fer_collection_num": 9, "fer_section_num": 5, "nw_item_code": "NW-023", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Разные металлоконструкции"},
    {"fer_collection_num": 9, "fer_section_num": 6, "nw_item_code": "NW-022", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Спецназначение — вне скоупа"},
    {"fer_collection_num": 9, "fer_section_num": 7, "nw_item_code": "NW-022", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "АЭС — вне скоупа"},
    {"fer_collection_num": 9, "fer_section_num": 8, "nw_item_code": "NW-022", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Ограждения периметра, средства защиты"},
    {"fer_collection_num": 9, "fer_section_num": 9, "nw_item_code": "NW-022", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Магистральные трубопроводы — вне скоупа"},
    {"fer_collection_num": 10, "fer_section_num": 1, "nw_item_code": "NW-021", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Деревянные дома (брус/каркас)"},
    {"fer_collection_num": 10, "fer_section_num": 1, "nw_item_code": "NW-068", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Стропильная система"},
    {"fer_collection_num": 10, "fer_section_num": 1, "nw_item_code": "NW-024", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Стены деревянные"},
    {"fer_collection_num": 10, "fer_section_num": 2, "nw_item_code": "NW-021", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Сборка домокомплекта (СИП/каркас)"},
    {"fer_collection_num": 10, "fer_section_num": 2, "nw_item_code": "NW-022", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Общественные здания из заводских деталей"},
    {"fer_collection_num": 10, "fer_section_num": 3, "nw_item_code": "NW-022", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Градирни — промстрой"},
    {"fer_collection_num": 10, "fer_section_num": 4, "nw_item_code": "NW-026", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "ГКЛ-перегородки"},
    {"fer_collection_num": 10, "fer_section_num": 4, "nw_item_code": "NW-030", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "ГКЛ как черновая отделка"},
    {"fer_collection_num": 10, "fer_section_num": 5, "nw_item_code": "NW-026", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "ГКЛ-перегородки/потолки/облицовки"},
    {"fer_collection_num": 10, "fer_section_num": 5, "nw_item_code": "NW-030", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "ГКЛ-облицовка стен/потолков как черновая отделка"},
    {"fer_collection_num": 10, "fer_section_num": 5, "nw_item_code": "NW-033", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Подвесные потолки = ремонт потолков"},
    {"fer_collection_num": 10, "fer_section_num": 6, "nw_item_code": "NW-026", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "ГВЛ-перегородки/потолки/облицовки"},
    {"fer_collection_num": 10, "fer_section_num": 6, "nw_item_code": "NW-030", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "ГВЛ как черновая отделка"},
    {"fer_collection_num": 10, "fer_section_num": 7, "nw_item_code": "NW-026", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "АЦП-перегородки"},
    {"fer_collection_num": 10, "fer_section_num": 7, "nw_item_code": "NW-030", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "АЦП-облицовка"},
    {"fer_collection_num": 11, "fer_section_num": 1, "nw_item_code": "NW-032", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Все типы полов"},
    {"fer_collection_num": 11, "fer_section_num": 1, "nw_item_code": "NW-030", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Стяжки и подготовка"},
    {"fer_collection_num": 12, "fer_section_num": 1, "nw_item_code": "NW-069", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Кровельное покрытие"},
    {"fer_collection_num": 12, "fer_section_num": 1, "nw_item_code": "NW-070", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Утепление кровли"},
    {"fer_collection_num": 12, "fer_section_num": 1, "nw_item_code": "NW-071", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Водосток"},
    {"fer_collection_num": 12, "fer_section_num": 1, "nw_item_code": "NW-068", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Стропильная система (если деревянная)"},
    {"fer_collection_num": 12, "fer_section_num": 1, "nw_item_code": "NW-072", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Ремонт кровли"},
    {"fer_collection_num": 13, "fer_section_num": 1, "nw_item_code": "NW-022", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Футеровка — промоборудование"},
    {"fer_collection_num": 13, "fer_section_num": 2, "nw_item_code": "NW-022", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Кислотоупорная кладка — промстрой"},
    {"fer_collection_num": 13, "fer_section_num": 3, "nw_item_code": "NW-019", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Лакокрасочная защита фундамента"},
    {"fer_collection_num": 13, "fer_section_num": 3, "nw_item_code": "NW-031", "mapping_type": "partial", "confidence": "low", "is_primary": False, "notes": "Окраска как отделка"},
    {"fer_collection_num": 13, "fer_section_num": 4, "nw_item_code": "NW-022", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Гуммирование — промоборудование"},
    {"fer_collection_num": 13, "fer_section_num": 5, "nw_item_code": "NW-019", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Оклеечная гидроизоляция"},
    {"fer_collection_num": 13, "fer_section_num": 6, "nw_item_code": "NW-019", "mapping_type": "composite_part", "confidence": "low", "is_primary": True, "notes": "Подготовительные — composite"},
    {"fer_collection_num": 13, "fer_section_num": 7, "nw_item_code": "NW-019", "mapping_type": "composite_part", "confidence": "low", "is_primary": True, "notes": "Обезжиривание — composite"},
    {"fer_collection_num": 13, "fer_section_num": 8, "nw_item_code": "NW-019", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Разные работы"},
    {"fer_collection_num": 13, "fer_section_num": 9, "nw_item_code": "NW-022", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Металлизация — промоборудование"},
    {"fer_collection_num": 13, "fer_section_num": 10, "nw_item_code": "NW-032", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Спецполы для агрессивных сред"},
    {"fer_collection_num": 13, "fer_section_num": 11, "nw_item_code": "NW-023", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Антикоррозия металлокаркаса"},
    {"fer_collection_num": 14, "fer_section_num": 1, "nw_item_code": "NW-022", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Здания животноводческие — нежилое сельхоз"},
    {"fer_collection_num": 14, "fer_section_num": 2, "nw_item_code": "NW-022", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Теплицы и овощехранилища"},
    {"fer_collection_num": 15, "fer_section_num": 1, "nw_item_code": "NW-031", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Облицовка как чистовая отделка"},
    {"fer_collection_num": 15, "fer_section_num": 1, "nw_item_code": "NW-076", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Облицовка фасада"},
    {"fer_collection_num": 15, "fer_section_num": 1, "nw_item_code": "NW-034", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Ремонт стен"},
    {"fer_collection_num": 15, "fer_section_num": 1, "nw_item_code": "NW-077", "mapping_type": "partial", "confidence": "medium", "is_primary": False, "notes": "Ремонт фасадной облицовки"},
    {"fer_collection_num": 15, "fer_section_num": 2, "nw_item_code": "NW-030", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Штукатурка как черновая отделка"},
    {"fer_collection_num": 15, "fer_section_num": 2, "nw_item_code": "NW-074", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Штукатурный фасад"},
    {"fer_collection_num": 15, "fer_section_num": 2, "nw_item_code": "NW-034", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Ремонт стен"},
    {"fer_collection_num": 15, "fer_section_num": 2, "nw_item_code": "NW-077", "mapping_type": "partial", "confidence": "medium", "is_primary": False, "notes": "Ремонт штукатурного фасада"},
    {"fer_collection_num": 15, "fer_section_num": 3, "nw_item_code": "NW-031", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "Лепные работы как чистовая отделка"},
    {"fer_collection_num": 15, "fer_section_num": 4, "nw_item_code": "NW-031", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Малярные работы"},
    {"fer_collection_num": 15, "fer_section_num": 4, "nw_item_code": "NW-034", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Окраска стен"},
    {"fer_collection_num": 15, "fer_section_num": 4, "nw_item_code": "NW-033", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Окраска потолков"},
    {"fer_collection_num": 15, "fer_section_num": 5, "nw_item_code": "NW-031", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Стекольные работы (остекление)"},
    {"fer_collection_num": 15, "fer_section_num": 6, "nw_item_code": "NW-031", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Обои"},
    {"fer_collection_num": 15, "fer_section_num": 7, "nw_item_code": "NW-031", "mapping_type": "direct", "confidence": "low", "is_primary": True, "notes": "Прочие отделочные"},
    {"fer_collection_num": 16, "fer_section_num": 1, "nw_item_code": "NW-046", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Чугунные водопроводные"},
    {"fer_collection_num": 16, "fer_section_num": 1, "nw_item_code": "NW-047", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Чугунные канализационные"},
    {"fer_collection_num": 16, "fer_section_num": 2, "nw_item_code": "NW-046", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Стальные водопровод/отопление"},
    {"fer_collection_num": 16, "fer_section_num": 2, "nw_item_code": "NW-045", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Стальные отопление"},
    {"fer_collection_num": 16, "fer_section_num": 3, "nw_item_code": "NW-046", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Металлополимерные"},
    {"fer_collection_num": 16, "fer_section_num": 3, "nw_item_code": "NW-045", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Тёплый пол/радиаторы"},
    {"fer_collection_num": 16, "fer_section_num": 4, "nw_item_code": "NW-046", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Пластиковые водопровод"},
    {"fer_collection_num": 16, "fer_section_num": 4, "nw_item_code": "NW-047", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Пластиковая канализация"},
    {"fer_collection_num": 16, "fer_section_num": 4, "nw_item_code": "NW-045", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Пластик в системах отопления"},
    {"fer_collection_num": 16, "fer_section_num": 5, "nw_item_code": "NW-046", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Арматура водопровода"},
    {"fer_collection_num": 16, "fer_section_num": 5, "nw_item_code": "NW-045", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Арматура отопления"},
    {"fer_collection_num": 16, "fer_section_num": 6, "nw_item_code": "NW-046", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Водомерные узлы"},
    {"fer_collection_num": 16, "fer_section_num": 7, "nw_item_code": "NW-046", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Сантехарматура и испытания"},
    {"fer_collection_num": 16, "fer_section_num": 7, "nw_item_code": "NW-047", "mapping_type": "direct", "confidence": "high", "is_primary": False, "notes": "Сантехника канализации"},
    {"fer_collection_num": 16, "fer_section_num": 8, "nw_item_code": "NW-046", "mapping_type": "direct", "confidence": "low", "is_primary": True, "notes": "Прочие"},
    {"fer_collection_num": 17, "fer_section_num": 1, "nw_item_code": "NW-046", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Внутренний водопровод"},
    {"fer_collection_num": 17, "fer_section_num": 1, "nw_item_code": "NW-047", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Внутренняя канализация"},
    {"fer_collection_num": 18, "fer_section_num": 1, "nw_item_code": "NW-045", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Котлы"},
    {"fer_collection_num": 18, "fer_section_num": 2, "nw_item_code": "NW-045", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Водоподогреватели/бойлеры"},
    {"fer_collection_num": 18, "fer_section_num": 3, "nw_item_code": "NW-045", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Радиаторы и приборы отопления"},
    {"fer_collection_num": 18, "fer_section_num": 4, "nw_item_code": "NW-045", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Расширительные баки"},
    {"fer_collection_num": 18, "fer_section_num": 5, "nw_item_code": "NW-045", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Циркуляционные насосы"},
    {"fer_collection_num": 18, "fer_section_num": 6, "nw_item_code": "NW-045", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Вводные устройства"},
    {"fer_collection_num": 18, "fer_section_num": 7, "nw_item_code": "NW-045", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "КИП и краны воздушные"},
    {"fer_collection_num": 19, "fer_section_num": 0, "nw_item_code": "NW-050", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Внутреннее газоснабжение здания (нет деления на разделы в ФЕРн)"},
    {"fer_collection_num": 20, "fer_section_num": 1, "nw_item_code": "NW-048", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Воздуховоды металлические"},
    {"fer_collection_num": 20, "fer_section_num": 2, "nw_item_code": "NW-048", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Конструктивные элементы вентиляции"},
    {"fer_collection_num": 20, "fer_section_num": 3, "nw_item_code": "NW-048", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Вентиляторы"},
    {"fer_collection_num": 20, "fer_section_num": 4, "nw_item_code": "NW-048", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Калориферы"},
    {"fer_collection_num": 20, "fer_section_num": 5, "nw_item_code": "NW-048", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Фильтрующие устройства"},
    {"fer_collection_num": 20, "fer_section_num": 6, "nw_item_code": "NW-048", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Кондиционеры"},
    {"fer_collection_num": 21, "fer_section_num": 1, "nw_item_code": "NW-001", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Бытовки/ИЗС временные — оснащение площадки"},
    {"fer_collection_num": 21, "fer_section_num": 2, "nw_item_code": "NW-001", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Временные сети — composite"},
    {"fer_collection_num": 21, "fer_section_num": 3, "nw_item_code": "NW-001", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Подкрановые пути — composite"},
    {"fer_collection_num": 22, "fer_section_num": 1, "nw_item_code": "NW-060", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Укладка наружного водопровода"},
    {"fer_collection_num": 22, "fer_section_num": 1, "nw_item_code": "NW-004", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Земляная часть траншей"},
    {"fer_collection_num": 22, "fer_section_num": 2, "nw_item_code": "NW-060", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Антикор стальных труб"},
    {"fer_collection_num": 22, "fer_section_num": 3, "nw_item_code": "NW-060", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Арматура"},
    {"fer_collection_num": 22, "fer_section_num": 4, "nw_item_code": "NW-060", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Водопроводные колодцы"},
    {"fer_collection_num": 22, "fer_section_num": 5, "nw_item_code": "NW-060", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "Бестраншейная прокладка (ГНБ)"},
    {"fer_collection_num": 22, "fer_section_num": 6, "nw_item_code": "NW-060", "mapping_type": "direct", "confidence": "low", "is_primary": True, "notes": "Прочие"},
    {"fer_collection_num": 23, "fer_section_num": 1, "nw_item_code": "NW-061", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Бытовая наружная канализация"},
    {"fer_collection_num": 23, "fer_section_num": 1, "nw_item_code": "NW-062", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Ливневая канализация"},
    {"fer_collection_num": 23, "fer_section_num": 1, "nw_item_code": "NW-004", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Траншеи"},
    {"fer_collection_num": 23, "fer_section_num": 2, "nw_item_code": "NW-061", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "Гидроизоляция бетонных труб"},
    {"fer_collection_num": 23, "fer_section_num": 3, "nw_item_code": "NW-061", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Канализационные колодцы"},
    {"fer_collection_num": 23, "fer_section_num": 3, "nw_item_code": "NW-062", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Ливневые колодцы"},
    {"fer_collection_num": 23, "fer_section_num": 4, "nw_item_code": "NW-061", "mapping_type": "direct", "confidence": "low", "is_primary": True, "notes": "Прочие"},
    {"fer_collection_num": 24, "fer_section_num": 1, "nw_item_code": "NW-063", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Наружные тепловые сети"},
    {"fer_collection_num": 24, "fer_section_num": 1, "nw_item_code": "NW-004", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Траншеи"},
    {"fer_collection_num": 24, "fer_section_num": 2, "nw_item_code": "NW-066", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Городские/поселковые газопроводы"},
    {"fer_collection_num": 24, "fer_section_num": 2, "nw_item_code": "NW-004", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Траншеи"},
    {"fer_collection_num": 24, "fer_section_num": 3, "nw_item_code": "NW-063", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Золошлакопроводы — ТЭС/промстрой"},
    {"fer_collection_num": 26, "fer_section_num": 1, "nw_item_code": "NW-070", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Теплоизоляция кровли"},
    {"fer_collection_num": 26, "fer_section_num": 1, "nw_item_code": "NW-073", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Теплоизоляция фасада"},
    {"fer_collection_num": 26, "fer_section_num": 1, "nw_item_code": "NW-020", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Утепление фундамента"},
    {"fer_collection_num": 26, "fer_section_num": 2, "nw_item_code": "NW-022", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Огнезащита — composite по конструкциям"},
    {"fer_collection_num": 27, "fer_section_num": 1, "nw_item_code": "NW-083", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Укрепленные грунтом основания — преим. магистрали"},
    {"fer_collection_num": 27, "fer_section_num": 2, "nw_item_code": "NW-079", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "Дренаж"},
    {"fer_collection_num": 27, "fer_section_num": 2, "nw_item_code": "NW-062", "mapping_type": "partial", "confidence": "medium", "is_primary": False, "notes": "Водосбросы"},
    {"fer_collection_num": 27, "fer_section_num": 3, "nw_item_code": "NW-083", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Реконструкция дорожных покрытий — вне скоупа"},
    {"fer_collection_num": 27, "fer_section_num": 4, "nw_item_code": "NW-083", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Подстилающие слои дорожек"},
    {"fer_collection_num": 27, "fer_section_num": 5, "nw_item_code": "NW-083", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "Мостовые/брусчатка"},
    {"fer_collection_num": 27, "fer_section_num": 6, "nw_item_code": "NW-083", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Магистральные основания — вне скоупа"},
    {"fer_collection_num": 27, "fer_section_num": 7, "nw_item_code": "NW-083", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Дорожки и тротуары — благоустройство"},
    {"fer_collection_num": 27, "fer_section_num": 8, "nw_item_code": "NW-083", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Краевые полосы магистралей — вне скоупа"},
    {"fer_collection_num": 27, "fer_section_num": 9, "nw_item_code": "NW-083", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Обустройство дорог — знаки/ограждения"},
    {"fer_collection_num": 27, "fer_section_num": 10, "nw_item_code": "NW-083", "mapping_type": "composite_part", "confidence": "low", "is_primary": True, "notes": "Приготовление материалов — composite"},
    {"fer_collection_num": 27, "fer_section_num": 11, "nw_item_code": "NW-083", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Болотные дороги — вне скоупа"},
    {"fer_collection_num": 27, "fer_section_num": 12, "nw_item_code": "NW-001", "mapping_type": "partial", "confidence": "medium", "is_primary": True, "notes": "Временные дороги стройплощадки"},
    {"fer_collection_num": 33, "fer_section_num": 1, "nw_item_code": "NW-064", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "ВЛ 35-1150 кВ — магистрали"},
    {"fer_collection_num": 33, "fer_section_num": 2, "nw_item_code": "NW-064", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "ОРУ 35-1150 кВ — магистрали"},
    {"fer_collection_num": 33, "fer_section_num": 3, "nw_item_code": "NW-064", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Сопутств. для ВЛ 35+"},
    {"fer_collection_num": 33, "fer_section_num": 4, "nw_item_code": "NW-064", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "ЛЭП 0.38-35 кВ и ТП — подключение объектов"},
    {"fer_collection_num": 33, "fer_section_num": 5, "nw_item_code": "NW-065", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Опоры наружного освещения"},
    {"fer_collection_num": 34, "fer_section_num": 1, "nw_item_code": "NW-067", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Сооружения связи/радио/ТВ — крупная инфраструктура"},
    {"fer_collection_num": 34, "fer_section_num": 2, "nw_item_code": "NW-067", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Проводная связь — кабельные линии"},
    {"fer_collection_num": 46, "fer_section_num": 1, "nw_item_code": "NW-043", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Усиление несущих"},
    {"fer_collection_num": 46, "fer_section_num": 1, "nw_item_code": "NW-044", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Усиление фундамента"},
    {"fer_collection_num": 46, "fer_section_num": 2, "nw_item_code": "NW-042", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Замена несущих"},
    {"fer_collection_num": 46, "fer_section_num": 3, "nw_item_code": "NW-035", "mapping_type": "composite_part", "confidence": "medium", "is_primary": True, "notes": "Сверление/пробивка — сопутствующее"},
    {"fer_collection_num": 46, "fer_section_num": 4, "nw_item_code": "NW-012", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Разборка перегородок/конструкций"},
    {"fer_collection_num": 46, "fer_section_num": 4, "nw_item_code": "NW-035", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Капремонт конструкций"},
    {"fer_collection_num": 46, "fer_section_num": 4, "nw_item_code": "NW-014", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Разборка кровли"},
    {"fer_collection_num": 46, "fer_section_num": 4, "nw_item_code": "NW-013", "mapping_type": "partial", "confidence": "medium", "is_primary": False, "notes": "Демонтаж старых сетей при разборке"},
    {"fer_collection_num": 46, "fer_section_num": 5, "nw_item_code": "NW-001", "mapping_type": "composite_part", "confidence": "low", "is_primary": True, "notes": "Временные защитные ограждения — оснащение"},
    {"fer_collection_num": 46, "fer_section_num": 6, "nw_item_code": "NW-011", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Разборка зданий = снос"},
    {"fer_collection_num": 46, "fer_section_num": 6, "nw_item_code": "NW-015", "mapping_type": "direct", "confidence": "medium", "is_primary": False, "notes": "Вывоз мусора"},
    {"fer_collection_num": 46, "fer_section_num": 7, "nw_item_code": "NW-042", "mapping_type": "direct", "confidence": "medium", "is_primary": True, "notes": "Замена металлоконструкций сооружений"},
    {"fer_collection_num": 46, "fer_section_num": 8, "nw_item_code": "NW-035", "mapping_type": "partial", "confidence": "low", "is_primary": True, "notes": "Прочие реконструкционные"},
    {"fer_collection_num": 46, "fer_section_num": 9, "nw_item_code": "NW-035", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Реконструкция гидротехники — вне скоупа"},
    {"fer_collection_num": 47, "fer_section_num": 1, "nw_item_code": "NW-085", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Посадки"},
    {"fer_collection_num": 47, "fer_section_num": 1, "nw_item_code": "NW-086", "mapping_type": "direct", "confidence": "high", "is_primary": True, "notes": "Газоны и цветники"},
    {"fer_collection_num": 47, "fer_section_num": 2, "nw_item_code": "NW-085", "mapping_type": "out_of_scope_subscope", "confidence": "low", "is_primary": True, "notes": "Защитные лесонасаждения — массовое лесоводство"},
]


def upgrade():
    op.create_table(
        "nw_fer_mapping",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("fer_collection_num", sa.SmallInteger(), nullable=False),
        sa.Column("fer_section_num", sa.SmallInteger(), nullable=False),
        sa.Column(
            "nw_item_code",
            sa.String(length=10),
            sa.ForeignKey(f"{FER_SCHEMA}.nw_item.code", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("mapping_type", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.UniqueConstraint(
            "fer_collection_num", "fer_section_num", "nw_item_code",
            name="uq_nw_fer_mapping_section_nw",
        ),
        sa.CheckConstraint(
            "mapping_type IN ('direct','partial','composite_part','out_of_scope_subscope')",
            name="ck_nw_fer_mapping_type",
        ),
        sa.CheckConstraint(
            "confidence IN ('high','medium','low')",
            name="ck_nw_fer_mapping_confidence",
        ),
        schema=FER_SCHEMA,
    )
    op.create_index(
        "ix_nw_fer_mapping_nw_code",
        "nw_fer_mapping", ["nw_item_code"],
        schema=FER_SCHEMA,
    )
    op.create_index(
        "ix_nw_fer_mapping_section",
        "nw_fer_mapping", ["fer_collection_num", "fer_section_num"],
        schema=FER_SCHEMA,
    )

    op.bulk_insert(
        sa.table(
            "nw_fer_mapping",
            sa.column("fer_collection_num", sa.SmallInteger),
            sa.column("fer_section_num", sa.SmallInteger),
            sa.column("nw_item_code", sa.String),
            sa.column("mapping_type", sa.String),
            sa.column("confidence", sa.String),
            sa.column("is_primary", sa.Boolean),
            sa.column("notes", sa.Text),
            schema=FER_SCHEMA,
        ),
        NW_FER_MAPPING,
    )


def downgrade():
    op.drop_index("ix_nw_fer_mapping_section", table_name="nw_fer_mapping", schema=FER_SCHEMA)
    op.drop_index("ix_nw_fer_mapping_nw_code", table_name="nw_fer_mapping", schema=FER_SCHEMA)
    op.drop_table("nw_fer_mapping", schema=FER_SCHEMA)
